name: Pull Request Template
description: Standardized template for pull requests.
title: "[PR]: <Summary of item>"
labels: ["pr"]

body:
  - type: markdown
    attributes:
      value: |
        ## Pull Request Checklist
        Please ensure the following before submitting your PR:
  
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a brief description of the changes in this PR.
    validations:
      required: true
  
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Provide any additional context or screenshots if applicable.
    validations:
      required: false
